version: '3.8'
services:
  web:
    build: .
    env_file: .env
    command: bundle exec rails server -p 3000 -b '0.0.0.0'
    volumes:
      - .:/app
      - gem-local:/usr/local/bundle
      - node-local:/app/node_modules
      - /app/tmp
    ports:
      - '3000:3000'
    depends_on:
      - db
    stdin_open: true
    tty: true

  db:
    image: mysql:5.7
    ports:
      - '${DB_PORT:-3306}:3306'
    environment:
      MYSQL_DATABASE: root
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    volumes:
      - db-local:/var/lib/mysql
    tty: true

  webpacker:
    build: .
    command: ./bin/webpack-dev-server
    ports:
      - '3035:3035'
    depends_on:
      - web
    volumes:
      - .:/app
      - node-local:/app/node_modules
    environment:
      - WEBPACKER_DEV_SERVER_HOST=0.0.0.0

volumes:
  db-local:
    driver: "local"
  gem-local:
    driver: "local"
  node-local:
    driver: "local"
