default: &default
  adapter: mysql2
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch('DB_USERNAME', 'root') %>
  password: <%= ENV.fetch('DB_PASSWORD', '') %>
  host:     <%= ENV.fetch('DB_HOST', 'db') %>
  charset: utf8mb4
  encoding: utf8mb4
  collation: utf8mb4_general_ci
  port: <%= ENV.fetch('DB_PORT', '3306') %>

development:
  <<: *default
  database: nullab_db_devlopment

test:
  <<: *default
  database: nullab_db_test

production:
  <<: *default
  database: nullab_db_test
  username: <%= ENV.fetch('DB_USERNAME', 'root') %>
  password:    <%= ENV.fetch('DB_PASSWORD', '') %>
